### ISSUE TITLE
Serial USB interface testing

### ISSUE THREAD

**Issue by rrainey** [benkrasnow/DSKY_EL_replica#10]
I was wondering what hardware you run the https://github.com/benkrasnow/DSKY_EL_replica/blob/master/software%20-%20Processing.org/DSKY_serial_control_tester/DSKY_serial_control_tester.pde Arduino program.  You ran that on a Windows PC connecting to the Driver board with a USB A-to-microB cable, correct?

**Comment by benkrasnow** [comment]
Yup. Processing.org on a Windows PC, with a USB cable to the PCB.  Serial port connection over USB.

**Comment by rrainey** [comment]
Thanks for the info.
