### ISSUE TITLE
KiCad Driver Project SCH file does not include HV507 to connector wires

### ISSUE THREAD

**Issue by rrainey** [benkrasnow/DSKY_EL_replica#11]
I am working on adding current limiting resistors as we discussed and I'm just looking at the Driver schematic. There don't seem to be connecting wires between the HV507 output lines and the connectors. Was that an oversight in the SCH file that was committed or did you route each of those manually on the PCB design?

**Comment by benkrasnow** [comment]
Looks like I just connected them in the PCB design since the layout would dictate the best connection scheme.

**Comment by rrainey** [comment]
NP. With the placement of the HV507s relative to the connectors, I think I might "punt" and place the resistors on the segment board. I'm working on that now.
