### ISSUE TITLE
Common current limiting resistors

### ISSUE THREAD

**Issue by cjkeithley** [benkrasnow/DSKY_EL_replica#4]
Decided to open this as a new issue/question (rather than adding onto the closed BOM issue)

Hi Ben,

I was watching your video and noticed that you mentioned that you'd added some current limiting resistors to the HV507 outputs that drive common. But, I don't see these resistors on the driver or segment schematics... am I missing something or looking in the wrong place?

> I've been working non-stop on this project for a while, and want a
> rest to work on other things. I don't have time to make 10 glass panels, but
> if there is enough interest, it may make sense to contract some work out, and
> maybe do some work in my shop. I'll let you know.

I'm interested as well! I'd buy 2 or 3.

Thanks & best regards,

Craig

**Comment by benkrasnow** [comment]
You are correct:  I used current-limiting resistors to join together the HV507 outputs, but they are not listed on the schematic.  This change was made after the last revision (ie I haven't actually changed the CAD, even on my local copy.  I just cut the traces and soldered resistors in there.)  I was using values of about 47Kohm.
