### ISSUE TITLE
Current limiting resistor array modification

### ISSUE THREAD

**Issue by rrainey** [benkrasnow/DSKY_EL_replica#8]
I worked this change up last night.  Sixteen 0402 75K (or 100K) resistors. 
CircuitHub will make a batch of 10 unpopulated boards for about $220 and 20 for only $20 more.  Want any?

I can send you a pull request with the modifications.

<img width="729" alt="new-01" src="https://user-images.githubusercontent.com/271126/86825205-b4b88980-c054-11ea-9a5b-8b33d78182ab.PNG">
<img width="792" alt="new-02" src="https://user-images.githubusercontent.com/271126/86825235-bd10c480-c054-11ea-9557-e29b9f155788.PNG">

**Comment by benkrasnow** [comment]
Sure send a pull request for the resistors.  I haven't worked on the DSKY in quite a while, so don't have a need for PCBs.  I think you'll find a lot of folks that want to buy them, though!

**Comment by rrainey** [comment]
Great. I just submitted the pull request. I'll close this Issue.
